-- =============================================================================
-- V10 — Quiz Module Schema (Learnova)
-- Bảng lưu trữ bài kiểm tra, câu hỏi trắc nghiệm và lượt làm bài của học viên.
-- Phục vụ 2 US: US-07 (Instructor soạn quiz) và US-20 (Learner làm quiz & chấm điểm).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. quizzes — Bài kiểm tra gắn 1–1 với Lesson có content_type = 'QUIZ' (BR-15)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quizzes (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id      BIGINT         NOT NULL,
    title          VARCHAR(255)   NOT NULL,
    passing_score  NUMERIC(5,2)   NOT NULL DEFAULT 80.00,
    max_attempts   INTEGER        DEFAULT 3,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ,

    CONSTRAINT uq_quizzes_lesson UNIQUE (lesson_id),
    CONSTRAINT fk_quizzes_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE,
    CONSTRAINT ck_quizzes_passing_score CHECK (passing_score >= 0.00 AND passing_score <= 100.00),
    CONSTRAINT ck_quizzes_max_attempts  CHECK (max_attempts IS NULL OR max_attempts > 0)
);

CREATE INDEX IF NOT EXISTS idx_quizzes_lesson ON quizzes (lesson_id);

-- ---------------------------------------------------------------------------
-- 2. quiz_questions — Câu hỏi trong bài kiểm tra (lưu options dạng JSONB)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quiz_questions (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id        BIGINT         NOT NULL,
    question_text  TEXT           NOT NULL,
    question_type  VARCHAR(30)    NOT NULL,
    options_json   JSONB          NOT NULL,
    points         NUMERIC(5,2)   NOT NULL DEFAULT 1.00,
    position       INTEGER        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ,

    CONSTRAINT fk_quiz_questions_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    CONSTRAINT ck_quiz_questions_type CHECK (question_type IN ('SINGLE_CHOICE', 'MULTIPLE_CHOICE')),
    CONSTRAINT ck_quiz_questions_points CHECK (points > 0.00)
);

CREATE INDEX IF NOT EXISTS idx_quiz_questions_quiz_pos ON quiz_questions (quiz_id, position);

-- ---------------------------------------------------------------------------
-- 3. quiz_attempts — Lượt làm bài & nộp bài của học viên (lưu snapshot bài nộp)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quiz_attempts (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id        BIGINT         NOT NULL,
    learner_id     BIGINT         NOT NULL,
    answers_json   JSONB          NOT NULL,
    score          NUMERIC(5,2)   NOT NULL DEFAULT 0.00,
    is_passed      BOOLEAN        NOT NULL DEFAULT FALSE,
    submitted_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_quiz_attempts_quiz    FOREIGN KEY (quiz_id)    REFERENCES quizzes(id) ON DELETE CASCADE,
    CONSTRAINT fk_quiz_attempts_learner FOREIGN KEY (learner_id) REFERENCES users(id)   ON DELETE CASCADE,
    CONSTRAINT ck_quiz_attempts_score   CHECK (score >= 0.00 AND score <= 100.00)
);

CREATE INDEX IF NOT EXISTS idx_quiz_attempts_quiz_learner ON quiz_attempts (quiz_id, learner_id, submitted_at DESC);
