-- =============================================================================
-- V11 — Hệ thống Hỏi & Đáp Q&A Khóa học và Bài học (Learnova - US-21)
-- =============================================================================

CREATE TABLE IF NOT EXISTS course_questions (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id        BIGINT         NOT NULL,
    lesson_id        BIGINT         NOT NULL,
    user_id          BIGINT         NOT NULL,
    title            VARCHAR(255)   NOT NULL,
    content          TEXT           NOT NULL,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_course_questions_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_questions_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_questions_user   FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_course_questions_course_lesson ON course_questions (course_id, lesson_id);
CREATE INDEX IF NOT EXISTS idx_course_questions_course ON course_questions (course_id);
CREATE INDEX IF NOT EXISTS idx_course_questions_user ON course_questions (user_id);
CREATE INDEX IF NOT EXISTS idx_course_questions_created ON course_questions (created_at DESC);

CREATE TABLE IF NOT EXISTS course_answers (
    id                   BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id          BIGINT         NOT NULL,
    user_id              BIGINT         NOT NULL,
    content              TEXT           NOT NULL,
    is_instructor_reply  BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_course_answers_question FOREIGN KEY (question_id) REFERENCES course_questions(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_answers_user     FOREIGN KEY (user_id)     REFERENCES users(id)            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_course_answers_question ON course_answers (question_id);
CREATE INDEX IF NOT EXISTS idx_course_answers_user ON course_answers (user_id);
CREATE INDEX IF NOT EXISTS idx_course_answers_created ON course_answers (created_at ASC);
