-- =============================================================================
-- V12 — Content Delivery (US-15) & Knowledge Tracking (US-17)
-- Yêu cầu: PostgreSQL >= 14 (kiểu int4multirange, hàm unnest(multirange))
-- Chạy SAU Task 0c (backfill duration_seconds) — duration_seconds phải đáng tin
-- trước khi backfill coverage bên dưới dùng nó làm mẫu số.
--
-- Số hiệu V12 (không phải V10 như thiết kế gốc): V10 đã bị nhánh quiz module
-- (V10__create_quiz_tables.sql, chưa merge vào main tính đến lúc viết file này)
-- chiếm; DB dev dùng chung còn có một migration "11" chưa rõ nguồn gốc không
-- tương ứng file nào trong repo. Cần rà soát lại thứ tự thật khi các nhánh merge.
-- =============================================================================

-- §5.3 — Mở rộng lesson_progress ----------------------------------------------
ALTER TABLE lesson_progress
    ADD COLUMN last_position_seconds INT            NOT NULL DEFAULT 0,
    ADD COLUMN max_position_seconds  INT            NOT NULL DEFAULT 0,
    ADD COLUMN watched_ranges        int4multirange NOT NULL DEFAULT '{}'::int4multirange,
    ADD COLUMN watched_seconds       INT            NOT NULL DEFAULT 0,
    ADD COLUMN coverage_percent      NUMERIC(5,2)   NOT NULL DEFAULT 0.00,
    ADD COLUMN completion_source     VARCHAR(20),
    ADD COLUMN first_started_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    ADD COLUMN updated_at            TIMESTAMPTZ    NOT NULL DEFAULT now();

-- completed_at: NOT NULL -> NULL. Dòng cũ đều mang nghĩa "đã hoàn thành" nên giữ
-- nguyên giá trị; backfill coverage = 100% để không tụt tiến độ của học viên.
ALTER TABLE lesson_progress ALTER COLUMN completed_at DROP NOT NULL;
ALTER TABLE lesson_progress ALTER COLUMN completed_at DROP DEFAULT;

UPDATE lesson_progress lp
SET watched_ranges        = int4multirange(int4range(0, GREATEST(1, l.duration_seconds))),
    watched_seconds       = GREATEST(1, l.duration_seconds),
    max_position_seconds  = GREATEST(1, l.duration_seconds),
    coverage_percent      = 100.00,
    completion_source     = 'MANUAL'      -- không biết nguồn gốc thật của dữ liệu cũ
FROM lessons l
WHERE l.id = lp.lesson_id
  AND lp.completed_at IS NOT NULL;

ALTER TABLE lesson_progress
    ADD CONSTRAINT ck_lesson_progress_coverage
        CHECK (coverage_percent >= 0.00 AND coverage_percent <= 100.00),
    ADD CONSTRAINT ck_lesson_progress_position
        CHECK (last_position_seconds >= 0 AND max_position_seconds >= 0),
    ADD CONSTRAINT ck_lesson_progress_completion_source
        CHECK (completion_source IS NULL
               OR completion_source IN ('POSITION', 'MANUAL', 'QUIZ')),
    -- completed_at và completion_source đi cùng nhau
    ADD CONSTRAINT ck_lesson_progress_completion_pair
        CHECK ((completed_at IS NULL) = (completion_source IS NULL));

-- Sidebar learning workspace: nạp toàn bộ tiến độ 1 enrollment
CREATE INDEX idx_lesson_progress_enrollment_lesson
    ON lesson_progress (enrollment_id, lesson_id);

-- Nút "Tiếp tục học": lesson chạm gần nhất
CREATE INDEX idx_lesson_progress_recent
    ON lesson_progress (enrollment_id, updated_at DESC);

-- §4.x — Audit truy cập nội dung (điều tra chia sẻ link) ----------------------
CREATE TABLE content_access_logs (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,                   -- NULL = khách vãng lai xem preview
    lesson_id     BIGINT      NOT NULL,
    ticket_jti    VARCHAR(16) NOT NULL,
    scope         VARCHAR(20) NOT NULL,
    outcome       VARCHAR(30) NOT NULL,     -- GRANTED | TICKET_EXPIRED | TICKET_MISMATCH | ACCESS_DENIED
    client_ip     INET,
    user_agent    VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cal_user   FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE SET NULL,
    CONSTRAINT fk_cal_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
);

CREATE INDEX idx_cal_user_time   ON content_access_logs (user_id, created_at DESC);
CREATE INDEX idx_cal_outcome     ON content_access_logs (outcome, created_at DESC)
    WHERE outcome <> 'GRANTED';
