-- =============================================================================
-- V17 — Backward Design course authoring (expand phase)
--
-- This migration is intentionally additive. The application still reads and
-- writes quizzes through lessons, so removing quizzes.lesson_id, QUIZ lessons,
-- or LEARNING_OBJECTIVE bullets here would break the currently deployed code.
-- A later contract migration will remove those legacy structures after the
-- outcome/assessment APIs and services have been rolled out.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Stable course-level learning outcomes
-- ---------------------------------------------------------------------------
CREATE TABLE learning_outcomes (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id  BIGINT       NOT NULL,
    statement  VARCHAR(500) NOT NULL,
    position   INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_learning_outcomes_course
        FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT ck_learning_outcomes_statement
        CHECK (length(btrim(statement)) > 0),
    CONSTRAINT ck_learning_outcomes_position
        CHECK (position >= 0)
);

CREATE INDEX idx_learning_outcomes_course_position
    ON learning_outcomes (course_id, position)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- 2. Base assessment model. section_id stays nullable while authoring a draft.
-- ---------------------------------------------------------------------------
CREATE TABLE assessments (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id       BIGINT       NOT NULL,
    section_id      BIGINT,
    assessment_type VARCHAR(30)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    instructions    TEXT,
    position        INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT fk_assessments_course
        FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_assessments_section
        FOREIGN KEY (section_id) REFERENCES course_sections(id) ON DELETE SET NULL,
    CONSTRAINT ck_assessments_type
        CHECK (assessment_type IN ('QUIZ')),
    CONSTRAINT ck_assessments_title
        CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_assessments_position
        CHECK (position >= 0)
);

CREATE INDEX idx_assessments_course
    ON assessments (course_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_assessments_section_position
    ON assessments (section_id, position)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- 3. Intended alignment between outcomes, assessments, and lesson plans
-- ---------------------------------------------------------------------------
CREATE TABLE assessment_outcomes (
    assessment_id BIGINT NOT NULL,
    outcome_id    BIGINT NOT NULL,

    CONSTRAINT pk_assessment_outcomes PRIMARY KEY (assessment_id, outcome_id),
    CONSTRAINT fk_assessment_outcomes_assessment
        FOREIGN KEY (assessment_id) REFERENCES assessments(id) ON DELETE CASCADE,
    CONSTRAINT fk_assessment_outcomes_outcome
        FOREIGN KEY (outcome_id) REFERENCES learning_outcomes(id) ON DELETE RESTRICT
);

CREATE INDEX idx_assessment_outcomes_outcome
    ON assessment_outcomes (outcome_id);

CREATE TABLE lesson_outcomes (
    lesson_id  BIGINT NOT NULL,
    outcome_id BIGINT NOT NULL,

    CONSTRAINT pk_lesson_outcomes PRIMARY KEY (lesson_id, outcome_id),
    CONSTRAINT fk_lesson_outcomes_lesson
        FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_outcomes_outcome
        FOREIGN KEY (outcome_id) REFERENCES learning_outcomes(id) ON DELETE RESTRICT
);

CREATE INDEX idx_lesson_outcomes_outcome
    ON lesson_outcomes (outcome_id);

-- ---------------------------------------------------------------------------
-- 4. Assessment completion is separate from lesson progress
-- ---------------------------------------------------------------------------
CREATE TABLE assessment_progress (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id     BIGINT      NOT NULL,
    assessment_id     BIGINT      NOT NULL,
    completed_at      TIMESTAMPTZ NOT NULL,
    completion_source VARCHAR(20) NOT NULL DEFAULT 'QUIZ',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ,

    CONSTRAINT fk_assessment_progress_enrollment
        FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE CASCADE,
    CONSTRAINT fk_assessment_progress_assessment
        FOREIGN KEY (assessment_id) REFERENCES assessments(id) ON DELETE CASCADE,
    CONSTRAINT uq_assessment_progress_enrollment_assessment
        UNIQUE (enrollment_id, assessment_id),
    CONSTRAINT ck_assessment_progress_source
        CHECK (completion_source IN ('QUIZ'))
);

CREATE INDEX idx_assessment_progress_enrollment
    ON assessment_progress (enrollment_id);

-- ---------------------------------------------------------------------------
-- 5. Expand quiz tables. Both columns remain nullable during authoring drafts.
--    quizzes.assessment_id is nullable temporarily so the pre-refactor service
--    can continue creating quizzes through lesson_id during a rolling release.
-- ---------------------------------------------------------------------------
ALTER TABLE quizzes
    ADD COLUMN assessment_id BIGINT;

ALTER TABLE quizzes
    ADD CONSTRAINT fk_quizzes_assessment
        FOREIGN KEY (assessment_id) REFERENCES assessments(id) ON DELETE CASCADE,
    ADD CONSTRAINT uq_quizzes_assessment UNIQUE (assessment_id);

ALTER TABLE quiz_questions
    ADD COLUMN outcome_id BIGINT;

ALTER TABLE quiz_questions
    ADD CONSTRAINT fk_quiz_questions_outcome
        FOREIGN KEY (outcome_id) REFERENCES learning_outcomes(id) ON DELETE RESTRICT;

CREATE INDEX idx_quiz_questions_outcome
    ON quiz_questions (outcome_id);

-- ---------------------------------------------------------------------------
-- 6. Backfill display objectives into stable outcome records.
--    Keep the original bullets during the expand phase for old application code.
-- ---------------------------------------------------------------------------
INSERT INTO learning_outcomes (course_id, statement, position)
SELECT cb.course_id, cb.content, cb.position
FROM course_bullets cb
WHERE cb.bullet_type = 'LEARNING_OBJECTIVE'
ORDER BY cb.course_id, cb.position, cb.id;

-- ---------------------------------------------------------------------------
-- 7. Backfill one assessment per existing quiz while preserving quiz IDs,
--    questions, attempts, lesson links, and curriculum positions.
-- ---------------------------------------------------------------------------
INSERT INTO assessments (
    id,
    course_id,
    section_id,
    assessment_type,
    title,
    position,
    created_at,
    updated_at
)
SELECT
    q.id,
    cs.course_id,
    l.section_id,
    'QUIZ',
    COALESCE(NULLIF(btrim(q.title), ''), l.title),
    ROW_NUMBER() OVER (
        PARTITION BY l.section_id
        ORDER BY l.position, q.id
    ) - 1,
    q.created_at,
    q.updated_at
FROM quizzes q
JOIN lessons l
    ON l.id = q.lesson_id
JOIN course_sections cs
    ON cs.id = l.section_id;

-- Explicit assessment IDs were copied from quizzes; move the identity sequence
-- beyond the largest copied ID before new assessments are created.
SELECT setval(
    pg_get_serial_sequence('assessments', 'id'),
    COALESCE((SELECT MAX(id) FROM assessments), 1),
    EXISTS (SELECT 1 FROM assessments)
);

UPDATE quizzes
SET assessment_id = id;

-- Abort the transaction if any legacy quiz was not associated with exactly one
-- migrated assessment. A partial conversion must never be committed.
DO $$
DECLARE
    quiz_count             BIGINT;
    migrated_quiz_count    BIGINT;
BEGIN
    SELECT COUNT(*) INTO quiz_count FROM quizzes;

    SELECT COUNT(*)
    INTO migrated_quiz_count
    FROM quizzes q
    JOIN assessments a
      ON a.id = q.assessment_id
     AND a.assessment_type = 'QUIZ';

    IF quiz_count <> migrated_quiz_count THEN
        RAISE EXCEPTION
            'Backward Design migration aborted: % quizzes found but % assessments migrated',
            quiz_count,
            migrated_quiz_count;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 8. Preserve completion from either the legacy quiz lesson or a passed attempt.
-- ---------------------------------------------------------------------------
INSERT INTO assessment_progress (
    enrollment_id,
    assessment_id,
    completed_at,
    completion_source,
    created_at,
    updated_at
)
SELECT
    lp.enrollment_id,
    q.assessment_id,
    lp.completed_at,
    'QUIZ',
    COALESCE(lp.first_started_at, lp.completed_at),
    COALESCE(lp.updated_at, lp.completed_at)
FROM lesson_progress lp
JOIN quizzes q
    ON q.lesson_id = lp.lesson_id
WHERE lp.completed_at IS NOT NULL
ON CONFLICT (enrollment_id, assessment_id) DO UPDATE
SET completed_at = LEAST(assessment_progress.completed_at, EXCLUDED.completed_at),
    updated_at = GREATEST(
        COALESCE(assessment_progress.updated_at, assessment_progress.completed_at),
        COALESCE(EXCLUDED.updated_at, EXCLUDED.completed_at)
    );

INSERT INTO assessment_progress (
    enrollment_id,
    assessment_id,
    completed_at,
    completion_source,
    created_at,
    updated_at
)
SELECT
    e.id,
    q.assessment_id,
    MIN(qa.submitted_at),
    'QUIZ',
    MIN(qa.submitted_at),
    MIN(qa.submitted_at)
FROM quiz_attempts qa
JOIN quizzes q
    ON q.id = qa.quiz_id
JOIN assessments a
    ON a.id = q.assessment_id
JOIN enrollments e
    ON e.student_id = qa.learner_id
   AND e.course_id = a.course_id
WHERE qa.is_passed = TRUE
GROUP BY e.id, q.assessment_id
ON CONFLICT (enrollment_id, assessment_id) DO UPDATE
SET completed_at = LEAST(assessment_progress.completed_at, EXCLUDED.completed_at),
    updated_at = GREATEST(
        COALESCE(assessment_progress.updated_at, assessment_progress.completed_at),
        COALESCE(EXCLUDED.updated_at, EXCLUDED.completed_at)
    );

-- Contract phase (later migration, after application refactors):
--   * require quizzes.assessment_id and quiz_questions.outcome_id as applicable;
--   * stop reading LEARNING_OBJECTIVE bullets and remove their migrated copies;
--   * soft-delete legacy QUIZ lessons after progress reconciliation;
--   * remove quizzes.lesson_id and QUIZ from lessons.content_type;
--   * allow lessons.content_type to be null for lesson plans.
