-- =============================================================================
-- V1 — Initial schema (Learnova)
-- Chỉ tạo bảng `users`, khớp chính xác entity com.learnova.elearning.module.user.entity.User
-- (@Enumerated(STRING) => role/auth_provider lưu dạng VARCHAR; interests => JSONB).
-- Các module tiếp theo (course, enrollment, payment, ...) thêm migration riêng V2, V3, ...
-- =============================================================================

CREATE TABLE users (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR(150) NOT NULL,
    email            VARCHAR(150) NOT NULL,
    password_hash    VARCHAR(255),
    auth_provider    VARCHAR(20)  NOT NULL DEFAULT 'LOCAL',
    auth_provider_id VARCHAR(255),
    avatar_url       VARCHAR(500),
    role             VARCHAR(50)  NOT NULL DEFAULT 'LEARNER',
    bio              TEXT,
    interests        JSONB,
    expertise        VARCHAR(255),
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT uq_users_email UNIQUE (email)
);
