-- =============================================================================
-- V21 — Hệ thống Đánh giá & Nhận xét Khóa học (Course Rating & Review System)
-- =============================================================================

-- 1. Bổ sung cột rating_count trên bảng courses
ALTER TABLE courses ADD COLUMN IF NOT EXISTS rating_count INTEGER NOT NULL DEFAULT 0;

-- 2. Tạo bảng course_reviews
CREATE TABLE IF NOT EXISTS course_reviews (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    rating      SMALLINT     NOT NULL,
    comment     TEXT,
    status      VARCHAR(20)  NOT NULL DEFAULT 'APPROVED',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT fk_course_reviews_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_reviews_user   FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE,
    CONSTRAINT ck_course_reviews_rating CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT ck_course_reviews_status CHECK (status IN ('APPROVED', 'FLAGGED', 'REJECTED'))
);

-- 3. Đảm bảo mỗi học viên chỉ có tối đa 1 đánh giá active trên mỗi khóa học
CREATE UNIQUE INDEX IF NOT EXISTS uq_course_reviews_active_user_course
    ON course_reviews (course_id, user_id)
    WHERE deleted_at IS NULL;

-- 4. Đánh index hỗ trợ truy vấn phân trang và thống kê
CREATE INDEX IF NOT EXISTS idx_course_reviews_course_active ON course_reviews (course_id, rating) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_course_reviews_course_created ON course_reviews (course_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_course_reviews_user ON course_reviews (user_id);
