-- =============================================================================
-- V25 — Lưu trữ Đề xuất Khóa học AI (User AI Course Recommendations)
-- =============================================================================

-- 1. Bảng lưu phiên đề xuất AI gần nhất của từng user
CREATE TABLE IF NOT EXISTS user_ai_recommendations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    goal            TEXT,
    preferred_level VARCHAR(30),
    interests       VARCHAR(500),
    advice_summary  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_user_ai_rec_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_ai_rec_user UNIQUE (user_id)
);

-- 2. Bảng lưu các khóa học cụ thể được AI chọn (Top 3)
CREATE TABLE IF NOT EXISTS user_ai_recommendation_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    course_id         BIGINT NOT NULL,
    match_score       INTEGER NOT NULL,
    reason            TEXT NOT NULL,
    rank_order        INTEGER NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_ai_rec_items_rec FOREIGN KEY (recommendation_id) REFERENCES user_ai_recommendations(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_rec_items_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- 3. Đánh index tối ưu truy vấn
CREATE INDEX IF NOT EXISTS idx_user_ai_rec_user ON user_ai_recommendations (user_id);
CREATE INDEX IF NOT EXISTS idx_user_ai_rec_items_rec ON user_ai_recommendation_items (recommendation_id);
CREATE INDEX IF NOT EXISTS idx_user_ai_rec_items_course ON user_ai_recommendation_items (course_id);
