-- =============================================================================
-- V2 — Course Authoring
-- Bảng cho 2 US: tạo/sửa/đặt giá/publish khóa học và thêm bài học đa định dạng.
-- Quy ước theo V1: BIGINT IDENTITY, enum lưu VARCHAR + CHECK (khớp @Enumerated(STRING)
-- và ddl-auto=validate), thời gian TIMESTAMPTZ.
-- Video/tài liệu lưu bằng storage_key (không phải URL public) — BR-12.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- categories — danh mục khóa học
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150) NOT NULL,
    slug       VARCHAR(150) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

-- ---------------------------------------------------------------------------
-- courses — khóa học (gốc của nhánh nội dung)
-- ---------------------------------------------------------------------------
CREATE TABLE courses (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id     BIGINT        NOT NULL,
    category_id     BIGINT,
    title           VARCHAR(255)  NOT NULL,
    subtitle        VARCHAR(255),
    slug            VARCHAR(280)  NOT NULL,
    description     TEXT,
    thumbnail_key   VARCHAR(500),
    promo_video_key VARCHAR(500),
    language        VARCHAR(20)   NOT NULL DEFAULT 'vi',
    level           VARCHAR(20),
    price           NUMERIC(12,2) NOT NULL DEFAULT 0,
    status          VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    rating_avg      NUMERIC(3,2)  NOT NULL DEFAULT 0,
    total_students  INTEGER       NOT NULL DEFAULT 0,
    version         BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    published_at    TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT uq_courses_slug     UNIQUE (slug),
    CONSTRAINT fk_courses_lecturer FOREIGN KEY (lecturer_id) REFERENCES users(id),
    CONSTRAINT fk_courses_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT ck_courses_price    CHECK (price >= 0 AND price <= 10000000),
    CONSTRAINT ck_courses_level    CHECK (level IS NULL OR level IN ('BEGINNER','INTERMEDIATE','ADVANCED')),
    CONSTRAINT ck_courses_status   CHECK (status IN
        ('DRAFT','PENDING_REVIEW','APPROVED','REJECTED','PUBLISHED','UNPUBLISHED','SUSPENDED','ARCHIVED'))
);
CREATE INDEX idx_courses_lecturer ON courses (lecturer_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_courses_status   ON courses (status)      WHERE deleted_at IS NULL;
CREATE INDEX idx_courses_category ON courses (category_id);

-- ---------------------------------------------------------------------------
-- course_bullets — 3 khối mô tả kiểu Udemy (What you'll learn / Requirements / Who is this for)
-- ---------------------------------------------------------------------------
CREATE TABLE course_bullets (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT       NOT NULL,
    bullet_type VARCHAR(30)  NOT NULL,
    content     VARCHAR(500) NOT NULL,
    position    INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_course_bullets_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT ck_course_bullets_type   CHECK (bullet_type IN
        ('LEARNING_OBJECTIVE','REQUIREMENT','TARGET_AUDIENCE'))
);
CREATE INDEX idx_course_bullets_course ON course_bullets (course_id, bullet_type, position);

-- ---------------------------------------------------------------------------
-- course_status_logs — nhật ký đổi trạng thái khóa học
-- ---------------------------------------------------------------------------
CREATE TABLE course_status_logs (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT      NOT NULL,
    actor_id    BIGINT      NOT NULL,
    from_status VARCHAR(20),
    to_status   VARCHAR(20) NOT NULL,
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_status_logs_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_status_logs_actor  FOREIGN KEY (actor_id)  REFERENCES users(id)
);
CREATE INDEX idx_status_logs_course ON course_status_logs (course_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- course_sections — chương/phần trong khóa học
-- ---------------------------------------------------------------------------
CREATE TABLE course_sections (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT       NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    position    INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT fk_sections_course FOREIGN KEY (course_id) REFERENCES courses(id)
);
CREATE INDEX idx_sections_course_position ON course_sections (course_id, position) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- lessons — curriculum item (video / article / file / quiz)
-- ---------------------------------------------------------------------------
CREATE TABLE lessons (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id         BIGINT       NOT NULL,
    title              VARCHAR(255) NOT NULL,
    content_type       VARCHAR(20)  NOT NULL,
    storage_key        VARCHAR(500),
    original_file_name VARCHAR(255),
    file_size_bytes    BIGINT,
    mime_type          VARCHAR(100),
    upload_status      VARCHAR(20)  NOT NULL DEFAULT 'EMPTY',
    content_text       TEXT,
    duration_seconds   INTEGER      NOT NULL DEFAULT 0,
    is_preview         BOOLEAN      NOT NULL DEFAULT FALSE,
    position           INTEGER      NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ,
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT fk_lessons_section  FOREIGN KEY (section_id) REFERENCES course_sections(id),
    CONSTRAINT ck_lessons_type     CHECK (content_type  IN ('VIDEO','ARTICLE','FILE','QUIZ')),
    CONSTRAINT ck_lessons_upload   CHECK (upload_status IN ('EMPTY','PENDING','READY','FAILED')),
    CONSTRAINT ck_lessons_duration CHECK (duration_seconds >= 0),
    CONSTRAINT ck_lessons_size     CHECK (file_size_bytes IS NULL OR file_size_bytes > 0)
);
CREATE INDEX idx_lessons_section_position ON lessons (section_id, position) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- lesson_resources — tài liệu đính kèm một lesson (nhiều file/lesson)
-- ---------------------------------------------------------------------------
CREATE TABLE lesson_resources (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id          BIGINT       NOT NULL,
    title              VARCHAR(255) NOT NULL,
    storage_key        VARCHAR(500) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    file_size_bytes    BIGINT       NOT NULL,
    mime_type          VARCHAR(100),
    position           INTEGER      NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT fk_lesson_resources_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id),
    CONSTRAINT ck_lesson_resources_size   CHECK (file_size_bytes > 0)
);
CREATE INDEX idx_lesson_resources_lesson ON lesson_resources (lesson_id, position) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Seed danh mục ban đầu
-- ---------------------------------------------------------------------------
INSERT INTO categories (name, slug) VALUES
    ('Lập trình Web',    'lap-trinh-web'),
    ('Lập trình Mobile', 'lap-trinh-mobile'),
    ('Khoa học dữ liệu', 'khoa-hoc-du-lieu'),
    ('Thiết kế',         'thiet-ke'),
    ('Kinh doanh',       'kinh-doanh'),
    ('Ngoại ngữ',        'ngoai-ngu');
