-- =============================================================================
-- V6 — Đăng ký học và Tiến độ học tập (Learnova)
-- =============================================================================

CREATE TABLE enrollments (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     BIGINT         NOT NULL,
    course_id      BIGINT         NOT NULL,
    status         VARCHAR(30)    NOT NULL DEFAULT 'ACTIVE',
    progress       NUMERIC(5,2)   NOT NULL DEFAULT 0.00,
    enrolled_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    completed_at   TIMESTAMPTZ,
    
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_enrollments_course  FOREIGN KEY (course_id)  REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT uq_enrollments_student_course UNIQUE (student_id, course_id),
    CONSTRAINT ck_enrollments_status  CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_enrollments_progress CHECK (progress >= 0.00 AND progress <= 100.00)
);

CREATE INDEX idx_enrollments_student ON enrollments (student_id);
CREATE INDEX idx_enrollments_course  ON enrollments (course_id);

CREATE TABLE lesson_progress (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id  BIGINT         NOT NULL,
    lesson_id      BIGINT         NOT NULL,
    completed_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    
    CONSTRAINT fk_lesson_progress_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_progress_lesson     FOREIGN KEY (lesson_id)     REFERENCES lessons(id) ON DELETE CASCADE,
    CONSTRAINT uq_lesson_progress_enrollment_lesson UNIQUE (enrollment_id, lesson_id)
);

CREATE INDEX idx_lesson_progress_enrollment ON lesson_progress (enrollment_id);
