-- =============================================================================
-- V9 — Thẻ Quản lý Đơn Thanh toán PayOS (Learnova)
-- =============================================================================

CREATE TABLE payment_orders (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code       BIGINT         NOT NULL UNIQUE,
    student_id       BIGINT         NOT NULL,
    course_id        BIGINT         NOT NULL,
    amount           NUMERIC(12,2)  NOT NULL,
    status           VARCHAR(30)    NOT NULL DEFAULT 'PENDING',
    payment_link_id   VARCHAR(255),
    checkout_url     TEXT,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_payment_orders_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_orders_course  FOREIGN KEY (course_id)  REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT ck_payment_orders_status  CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'FAILED'))
);

CREATE INDEX idx_payment_orders_student ON payment_orders (student_id);
CREATE INDEX idx_payment_orders_course  ON payment_orders (course_id);
CREATE INDEX idx_payment_orders_order_code ON payment_orders (order_code);
